### PR TITLE
3.x support

### PR DESCRIPTION
**Pull request by vnitinv**
This changes also include Unit test framework https://travis-ci.org/vnitinv/ncclient/builds/74217872
110 TCs, around 80% code coverage

This pull request is bit different compared to #60 
1> We are using python module six (rather then writing our own)
2> We have left the default behavior of lxml.
3> 3.x UTs supporting the code

### CODE REVIEW

**Comment by leopoul** [comment]
Great job!!!!! Many many thnx!!! I like the approach with six; will go for it.

Moved the request to a new branch and performing tests: https://github.com/leopoul/ncclient/tree/v3
Want to make sure that every possible scenario with devices I have access to, is covered.
Have you tested on Juniper devices without the device_params?

Thnx
Leonidas

**Comment by vnitinv** [comment]
@leopoul I guess we missed testing without device_params. Will do it ASAP

**Comment by ktbyers** [comment]
@vnitinv @leopoul Any update on this PR? Anything holding this PR up?

**Comment by leopoul** [comment]
It's now on master branch, preparing to release it in v0.5.0

**Comment by ktbyers** [comment]
@leopoul @vnitinv Nice, thanks.

**Pull request merged**
