### PR TITLE
Fix: race condition during handshake

### PR DESCRIPTION
**Pull request by xavierhardy**
No message must be sent (except maybe the "hello" ack) before the client has received the "hello" message from the server.

### CODE REVIEW

**Comment by xavierhardy** [comment]
Of course, now some tests are broken. One of the tests consist in just sending a message.

Before I fix the tests (and add one to test the race condition), I would like to know what you think about my pull request. I have clearly seen the race condition happen when the "hello" message takes some time (2 seconds in my case) to be sent by the server.

**Comment by xavierhardy** [comment]
Can someone check please?

**Comment by leopoul** [comment]
Hi could you provide some more info about the server? I would like if possible to reproduce the issue.

**Comment by xavierhardy** [comment]
No, I can't because it would disclose which type of switch/router we are using, but this problem should be reproducible on any NETCONF server, it does not depend on the server's implementation.

**Comment by einarnn** [comment]
Xavier,

Looking at the code in question, I would say that rather than the fix you have applied, we need to look at this code:

https://github.com/xavierhardy/ncclient/blob/ba2a2e1d2a33e560dd99b0562a65b9c1f8db247a/ncclient/transport/ssh.py#L501-L518

The intent of that section seems to be that we wait there until we have received the hello message from the server so that we have the capabilities, and if we do not receive the sever capabilities then we should error out before getting to the if statement you have modified.

Cheers,

Einar

**Comment by maseev** [comment]
Correct me if I'm wrong, but according to [spec](https://tools.ietf.org/html/rfc6241#section-8.1) server and client don't have to wait for each other's hello messages that include their capabilities:

> Capabilities are advertised in messages sent by each peer during
   session establishment.  When the NETCONF session is opened, each peer
   (both client and server) MUST send a <hello> element containing a
   list of that peer's capabilities.
> ...
> Each peer sends its <hello> element simultaneously as soon as the
   connection is open.  A peer MUST NOT wait to receive the capability
   set from the other side before sending its own set.

Right now, it looks like ncclient is waiting for a server to send a ```hello``` message first which clearly violates the spec.

**Comment by einarnn** [comment]
@xavierhardy, I made a suggestion last year about where a change may be better made. Have you had time to look at it? Please let me know your thoughts.

**Comment by einarnn** [comment]
Closing this for now. @xavierhardy, please feel free to update this pull request and resubmit.

Cheers,

Einar

**Comment by xavierhardy** [comment]
Sorry for that, I did not have time to look at it again.

**Pull request closed without merging**
