### PR TITLE
Add notification support

### PR DESCRIPTION
**Pull request by jwwilcox**
This PR adds the ability to create NETCONF notification subscriptions and retrieve notifications from a queue when they are received.

### CODE REVIEW

**Comment by jwwilcox** [comment]
Looks like I've failed some Python 2.6 stuff. Will fix.

**Comment by jwwilcox** [comment]
Are there any changes I can make to make this more palatable to merge?

**Comment by leopoul** [comment]
Looks really good! Out of curiosity, could you provide a debug output from a device with notification capability? 

Thanks,
L.

**Comment by jwwilcox** [comment]
Sure. I've attached a debug log from a test I ran.

The test uses a custom RPC call to force the server to generate a notification. The server then just reflects that notification right back at us.
[ncclient_debug.txt](https://github.com/ncclient/ncclient/files/584961/ncclient_debug.txt)

**Comment by jgatkinsn** [comment]
+1

**Pull request merged**
