### PR TITLE
Add netconf:1.1 support plus get_schema RPC, please ignore #85 pull request

### PR DESCRIPTION
**Pull request by einarnn**
This pull requests contains the same content as #85, but I have resolved the issue that prevented an automatic merge. I work with the submitter (nnakamot) of the other pull request, and we have agreed to drop that one. Or you can reject it.

Cheers,

Einar

### CODE REVIEW

**Comment by leopoul** [comment]
Thank you very much Einar.
I'll check it and merge it in the weekend

Best,
Leonidas

**Comment by einarnn** [comment]
Thanks!

**Comment by einarnn** [comment]
Leonidas,

Any update on this? I have a few people who are waiting to get 1.1 functionality! I'm having to point them to my fork in the interim, but I'd rather not do that and would like to be able to point people to use pip install.

Cheers,

Einar

**Comment by einarnn** [comment]
Is there anything I can do to help further with this?

Cheers,

Einar

**Comment by leopoul** [comment]
Hi Einar,
Sorry for the delay; I'm trying to get a test env to test the PR plus had a big workload before holidays. Do you have a test env where I could be temporarily granted access?
For now I'll test that nothing breaks with NETCONF 1.0 supporting devices. 

Sorry again for the delay...

Best,
Leo

**Comment by einarnn** [comment]
Leonidas,

Sorry for the delay in getting back to you. Unfortunately, I don't have an environment that I can open up to you. However, there is a VirtualBox VM you can download that lets you play with netconf:base:1.1, which is the netopeer web guy demo. You can find the link on this page:

https://github.com/CESNET/Netopeer-GUI <https://github.com/CESNET/Netopeer-GUI>

Using yum, what I needed to install was:

A more modern version of libxml2-devel.
python27-pip
python27-virtualenv
pip install lxml==3.4.4 (I've had problems with others) into a virtualenv

...and then the specific version of ncclient for testing from the git repo, again into the virtualenv.

At that point I was able to run a number of sample apps, and with verbose debug logging on I verified that netconf:base:1.1 was being used after the initial capabilities negotiation.

Hope this helps!

Cheers,

Einar

**Comment by leopoul** [comment]
Great!! Thnx!! Will check it and merge

**Comment by leopoul** [comment]
Works for 1.1 but has broken for 1.0 - test with Juniper device. I'm investigating and will patch it

**Comment by leopoul** [comment]
Found it! Needed to include an extra check for:
```
urn:ietf:params:xml:ns:netconf:base:1.0
```
in server capabilities. Works now!

**Comment by leopoul** [comment]
Many thnx for this Einar! 
Tomorrow I'll do some extra checks on tools that depend on ncclient (eg. Junos PyEZ), I will version ncclient and push to pypi.

Best,
Leo

**Pull request merged**
