### PR TITLE
Add option to parse XML replies with huge text node (fixes #185)

### LINKED ISSUE #185: Exception when NETCONF response contains an XML text node > 10,000,000 bytes
By default, libxml2 >= 2.7 restricts XML text nodes to a maximum of 10,000,000 bytes (~9.5Mbytes). In turn, lxml uses this libxml2 default, but offers the `huge_tree` option:
http://lxml.de/parsing.html#parser-options

If a NETCONF response contains an XML text node with > 10,000,000 bytes this causes the following exception to be raised:
```
    return self._conn.rpc(rpc_cmd_e)._NCElement__doc
  File "/usr/local/lib/python2.7/dist-packages/ncclient/manager.py", line 172, in wrapper
    return self.execute(op_cls, *args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/ncclient/manager.py", line 232, in execute
    raise_mode=self._raise_mode).request(*args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/ncclient/operations/third_party/juniper/rpc.py", line 44, in request
    return self._request(rpc)
  File "/usr/local/lib/python2.7/dist-packages/ncclient/operations/rpc.py", line 339, in _request
    return NCElement(self._reply, self._device_handler.transform_reply())
  File "/usr/local/lib/python2.7/dist-packages/ncclient/xml_.py", line 153, in __init__
    self.__doc = self.remove_namespaces(self.__result)
  File "/usr/local/lib/python2.7/dist-packages/ncclient/xml_.py", line 201, in remove_namespaces
    self.__root = etree.fromstring(str(self.__transform(etree.parse(StringIO(str(rpc_reply))))))
  File "src/lxml/lxml.etree.pyx", line 3427, in lxml.etree.parse (src/lxml/lxml.etree.c:81117)
  File "src/lxml/parser.pxi", line 1828, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:118072)
  File "src/lxml/parser.pxi", line 1848, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:118341)
  File "src/lxml/parser.pxi", line 1736, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:117021)
  File "src/lxml/parser.pxi", line 1102, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:111265)
  File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105109)
  File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:106817)
  File "src/lxml/parser.pxi", line 635, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:105671)
  File "<string>", line 106044
lxml.etree.XMLSyntaxError: xmlSAX2Characters: huge text node, line 106044, column 1
```

This has been encountered when trying to retrieve a large Junos configuration file in set or text format, but the general issue is not specific to Junos.

### PR DESCRIPTION
**Pull request by sstancu**
Fixes #185 

This merge request adds a `huge_tree` paramater for the "Manager", which can be tweaked in multiple places:
* global level `manager.Manager.HUGE_TREE_DEFAULT`, in case the library is used by another library that cannot be modfied
* as a property for the `Manager` (the solution suggested in #186)
* at the RPC implementation level (e.g. `third_party.juniper.rpc.GetConfiguration` enables huge_tree support for non-xml configuration formats)

Note, that at least for lxml for Python 3.6, the xml parsing of `huge text node` is not triggered for huge text nodes that do not contain XML escaped characters (e.g. `&gt;` for `>`).

### CODE REVIEW

**Comment by sstancu** [comment]
Thanks for the merge.
Since we're actually using py-junos-eznc (which internally uses ncclient), I was wondering if it would be possible to have a new ncc relase with this fix .
This would allow me to make the necessary patches in py-junos-eznc (with reference to the presumably new ncclient release).

Thanks in advance for your prompt replies.

**Comment by einarnn** [comment]
Next week?

**Comment by sstancu** [comment]
A new release next week would be great, thanks!

**Comment by einarnn** [comment]
Just uploaded 0.6.5 to PyPi.

Cheers,

Einar

**Pull request merged**
