### PR TITLE
Add a call-home manager object

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by einarnn** [comment]
@jwwilcox, can you bring this PR up to date with the current state of the master branch?

Thanks!

**Comment by golmaal** [comment]
@einarnn - If I rebase this branch to latest master, would you consider merging this PR? 
Another duplicate issue seems to be waiting on it as well https://github.com/ncclient/ncclient/issues/334

**Comment by einarnn** [comment]
Yes, I would. Would also like to determine if #432 has any benefits compared to this approach.

**Comment by einarnn** [comment]
A more recent PR was accepted.

**Pull request closed without merging**
