### PR TITLE
Bugfix some unreasonable places in Dispatch

### PR DESCRIPTION
**Pull request by fredgan**
@einarnn Hi,
I found some unreasonable places in Dispatch as follows.
1. Dispatch RPC uses `GetReply` for its reply class, as you mentioned at #252.
2. It doesn't support the operations w/ `config` or `target` parameter, such as `edit-config`, `copy-config` and so on.

This PR fixes them. :-)

### CODE REVIEW

**Review by einarnn — COMMENTED** [review]
@fredgan, the code in `retrieve.py` is for **get** operations. By adding in `config` and `target`, you are changing the semantics of the classes in `retrieve.py`. What is the benefit of this?

**Comment by fredgan** [comment]
@einarnn , sorry for the delayed response.
https://github.com/ncclient/ncclient/blob/3bd7ce3177e747c307afd6340878ed0be8691cc6/ncclient/operations/retrieve.py#L207-L209.
The `rpc_command` does not indicate that it's only used for `get` operations. For users, they may think that the `rpc_command` parameter can specify any rpc command, not just `get` operations. so when they specify an `edit-config` operation or other operations with target/config parameters, `Dispatch` does not apply and even report some errors.

**Review by einarnn — CHANGES_REQUESTED** [review]
I think that what you're trying to achieve is what I'll call generic RPC behavior. IOW, a class that can be mapped to a call on the manager that can do **any** RPC.

Rather than changing an existing class to do more than originally intended, I think it would be better to have a concrete class in rpc.py that can be mapped into a function called `rpc` on the manager, and it takes either a string or an XML tree. This would just be sent with no extra parameters, and the reply would come back as an RPCReply object.

I'm suggesting this because I think that there should only be one way to do things, and I actually think that the `dispatch` call is something I'd rather deprecate if at all possible (this is probably not possible until **after** we declare a 1.0.0 release as I don't want to make any API breaking changes in `0.x.y`).

**Review by einarnn — APPROVED** [review]
Thanks for the updates!

**Comment by boxidau** [comment]
the addition of the rpc method in manager.py bypasses the _vendor_operations lookup in __getattr__ of manager.py - the juniper implementation specifies an rpc method which is not called because of this change - is there a recommended way to return to using the juniper rpc method rather than the genericRPC method or will this need a patch?

**Pull request merged**
